#!/bin/bash

#java -classpath ./classes:./lib/javafx.graphics.jar SimpleCommander
java --module-path $PATH_TO_FX --add-modules javafx.controls -classpath ./classes:./lib/laglibjava.jar SearchInTextFiles

